name: Build ComfyUI Desktop
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-windows:
    name: Build ComfyUI Desktop - PyTorch ${{ matrix.pytorch_version }}
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        pytorch_version: ['2.7', '2.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Show latest commit
        run: git log -1 --oneline
        shell: bash
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Node.js 20.18.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          $VERSION = (Get-Content pyproject.toml | Select-String '^version = "(.+)"').Matches.Groups[1].Value
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
          echo "Extracted ComfyUI-nunchaku version: $VERSION"
        shell: pwsh
      - name: Get latest nunchaku release version
        id: get_nunchaku_version
        run: |
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/nunchaku-tech/nunchaku/releases/latest" -Headers @{ "User-Agent" = "GitHub Actions" }
          $NUNCHAKU_VERSION = $response.tag_name -replace '^v', ''
          echo "nunchaku_version=$NUNCHAKU_VERSION" >> $env:GITHUB_OUTPUT
          echo "Latest nunchaku release: $NUNCHAKU_VERSION"
        shell: pwsh
      - name: Run build script
        run: |
          cd ..
          where python
          python --version
          where node
          node --version
          rm -rf desktop
          ComfyUI-nunchaku\.github\workflows\build_comfyui_desktop.cmd
        shell: cmd
        env:
          NUNCHAKU_VERSION: ${{ steps.get_nunchaku_version.outputs.nunchaku_version }}
          TORCH_VERSION: ${{ matrix.pytorch_version }}
      - name: List build output
        run: |
          Get-ChildItem -Path "..\desktop\dist" -ErrorAction SilentlyContinue | Format-Table Name, Length, LastWriteTime
        shell: pwsh
        if: always()
      - name: Copy and rename artifacts
        run: |
          dir ..\desktop\dist
          mkdir artifacts
          for %%f in (..\desktop\dist\*.zip) do (
            echo Renaming %%~nxf to ComfyUI-nunchaku-${{ steps.get_version.outputs.version }}-torch${{ matrix.pytorch_version }}-desktop-win.zip
            move "%%f" "artifacts\ComfyUI-nunchaku-${{ steps.get_version.outputs.version }}-torch${{ matrix.pytorch_version }}-desktop-win.zip"
          )
          dir artifacts
        shell: cmd
        if: success()
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-desktop-pytorch-${{ matrix.pytorch_version }}
          path: artifacts/*.zip
          retention-days: 7
        if: success()
      # - name: Upload Artifact to Existing Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: v${{ steps.get_version.outputs.version }}
      #     files: artifacts/*.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   if: success()
      - name: Clean up
        run: |
          cd ..
          rm -rf desktop
        shell: cmd
        if: always()
